(function(){'use strict';
var $=function(s){return document.querySelector(s)},state={token:'',name:'',isMaster:false,events:[],data:null};
function api(){return window.KanoonApp&&window.KanoonApp.api}
function toast(m,e){var t=window.KanoonApp&&window.KanoonApp.toast;if(t)(e?t.error:t.success)(m)}
function esc(s){return String(s==null?'':s).replace(/[&<>"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]})}
function login(){var f=$('#coachLoginForm');f.addEventListener('submit',function(e){e.preventDefault();var phone=$('#coachPhone').value.trim(),code=$('#coachCode').value.trim();if(!phone||!code)return;api().post({action:'loginCoach',phone:phone,code:code}).then(function(r){state.token=r.token;state.name=r.coach.name;state.isMaster=!!r.coach.isMaster;sessionStorage.setItem('coach_token',state.token);sessionStorage.setItem('coach_name',state.name);sessionStorage.setItem('coach_master',state.isMaster?'1':'0');$('#coachLogin').classList.add('hidden');$('#coachDashboard').classList.remove('hidden');$('#coachName').textContent=state.name;toggleStaff();load()}).catch(function(e){toast(e.message||'کد مربی نامعتبر است',1)})})}
function load(){api().get({action:'getDashboard',token:state.token}).then(function(r){state.data=r;state.events=r.events||[];renderStats(r.stats);renderEvents(state.events);renderRegs(r.registrations||[]);renderAttendance(r.attendance||[]);renderWarnings(r.warnings||[]);$('#gamePrize').value=r.prize||'به بیشترین رکورد هفته جایزه داده می شود'}).catch(function(e){toast(e.message||'خطا در بارگذاری داشبورد',1)})}
function renderStats(s){$('#coachStats').innerHTML=[['اعضای فعال',s.activeMembers],['در انتظار تایید',s.pendingRegistrations],['حضور امروز',s.todayAttendance],['اخطار ماه',s.monthWarnings]].map(function(x){return '<div class="coach-stat"><strong>'+Number(x[1]).toLocaleString('fa-IR')+'</strong><span>'+x[0]+'</span></div>'}).join('')}
function renderEvents(list){$('#eventsAdmin').innerHTML=list.length?list.map(function(e){return '<div class="admin-item"><img src="'+esc(e.imageUrl||'images/placeholder.svg')+'"><div class="admin-item-main"><strong>'+esc(e.title)+'</strong><small>'+esc(e.label||'رویداد')+' · '+esc(e.date||'')+'</small></div><div class="admin-actions"><button data-edit="'+esc(e.id)+'">ویرایش</button><button class="danger" data-del="'+esc(e.id)+'">حذف</button></div></div>'}).join(''):'<div class="empty"><p>هنوز رویدادی ثبت نشده</p></div>';document.querySelectorAll('[data-edit]').forEach(function(b){b.onclick=function(){editEvent(b.dataset.edit)}});document.querySelectorAll('[data-del]').forEach(function(b){b.onclick=function(){deleteEvent(b.dataset.del)}})}
function renderRegs(list){$('#registrationsAdmin').innerHTML=list.length?list.map(function(r){return '<div class="admin-item"><div class="admin-item-main"><strong>'+esc(r.firstName+' '+r.lastName)+'</strong><small>'+esc(r.phone)+' · '+esc(r.status)+'</small></div><div class="admin-actions">'+(r.status==='در انتظار تایید'?'<button data-ok="'+esc(r.id)+'">تایید</button><button class="danger" data-no="'+esc(r.id)+'">رد</button>':'')+'</div></div>'}).join(''):'<div class="empty"><p>ثبت‌نامی وجود ندارد</p></div>';document.querySelectorAll('[data-ok]').forEach(function(b){b.onclick=function(){setReg(b.dataset.ok,'تایید شد')}});document.querySelectorAll('[data-no]').forEach(function(b){b.onclick=function(){setReg(b.dataset.no,'رد شد')}})}
function setReg(id,status){api().post({action:'setRegistrationStatus',token:state.token,id:id,status:status}).then(function(){toast('وضعیت ثبت شد ✓');load()}).catch(function(e){toast(e.message,1)})}
function renderAttendance(rows){$('#attendanceAdmin').innerHTML=rows.length?rows.map(function(r){return '<div class="report-row"><span>'+esc(r.date)+'</span><span>'+esc(r.memberName)+'</span><span>'+esc(r.status)+'</span></div>'}).join(''):'<p class="muted">برای ماه جاری هنوز گزارشی ثبت نشده</p>'}
function renderWarnings(rows){$('#warningsAdmin').innerHTML=rows.length?rows.map(function(r){return '<div class="report-row"><span>'+esc(r.date)+'</span><span>'+esc(r.memberName)+' · '+esc(r.reason)+'</span><span>'+esc(r.responsibility)+'</span></div>'}).join(''):'<p class="muted">برای ماه جاری اخطاری ثبت نشده</p>'}
function openEditor(e){$('#eventEditor').classList.remove('hidden');$('#eventId').value=e?e.id:'';$('#eventTitle').value=e?e.title:'';$('#eventLabel').value=e?e.label:'';$('#eventDescription').value=e?e.description:'';$('#eventDate').value=e?e.date:'';$('#eventSort').value=e?e.sort||0:0;$('#eventPreview').textContent=e&&e.imageUrl?'تصویر فعلی ثبت شده':'تصویر جدید را انتخاب کن'}
function editEvent(id){var e=state.events.find(function(x){return x.id===id});if(e)openEditor(e)}
function deleteEvent(id){if(!confirm('این رویداد حذف شود؟'))return;api().post({action:'deleteEvent',token:state.token,id:id}).then(function(){toast('رویداد حذف شد');load()}).catch(function(e){toast(e.message,1)})}
function file64(file){return new Promise(function(resolve,reject){var r=new FileReader();r.onload=function(){resolve(String(r.result).split(',')[1])};r.onerror=reject;r.readAsDataURL(file)})}
async function saveEvent(){var btn=$('#saveEventBtn');btn.disabled=true;try{var imageId='',imageUrl='';var file=$('#eventImage').files[0];if(file){var up=await file64(file);var r=await api().post({action:'uploadEventImage',token:state.token,base64:up,mimeType:file.type});imageId=r.fileId;imageUrl=r.url}else{var old=state.events.find(function(x){return x.id===$('#eventId').value});if(old){imageId=old.imageId||'';imageUrl=old.imageUrl||''}}await api().post({action:'saveEvent',token:state.token,id:$('#eventId').value,title:$('#eventTitle').value,description:$('#eventDescription').value,label:$('#eventLabel').value,date:$('#eventDate').value,sort:Number($('#eventSort').value||0),imageId:imageId,imageUrl:imageUrl,active:true});toast('رویداد ذخیره شد ✓');$('#eventEditor').classList.add('hidden');load();loadSchedule()}catch(e){toast(e.message||'خطا در ذخیره رویداد',1)}finally{btn.disabled=false}}
function loadSchedule(){api().get({action:'listSchedule'}).then(function(r){var list=r.items||[];$('#scheduleAdmin').innerHTML=list.length?list.map(function(x){return '<div class="admin-item"><div class="admin-item-main"><strong>'+esc(x.day)+' · '+esc(x.title)+'</strong><small>'+esc(x.time)+' '+(x.location?'· '+esc(x.location):'')+'</small></div><div class="admin-actions"><button data-sedit="'+esc(x.id)+'">ویرایش</button><button class="danger" data-sdel="'+esc(x.id)+'">حذف</button></div></div>'}).join(''):'<div class="empty"><p>برنامه هفتگی خالی است</p></div>';document.querySelectorAll('[data-sedit]').forEach(function(b){b.onclick=function(){var x=list.find(function(y){return y.id===b.dataset.sedit});if(x){$('#scheduleEditor').classList.remove('hidden');$('#scheduleId').value=x.id;$('#scheduleDay').value=x.day;$('#scheduleTitle').value=x.title;$('#scheduleTime').value=x.time;$('#scheduleLocation').value=x.location;$('#scheduleSort').value=x.sort||0}}});document.querySelectorAll('[data-sdel]').forEach(function(b){b.onclick=function(){if(confirm('این برنامه حذف شود؟'))api().post({action:'deleteSchedule',token:state.token,id:b.dataset.sdel}).then(function(){toast('برنامه حذف شد');loadSchedule()})}})}).catch(function(){})}
function setupSchedule(){if(!$('#newScheduleBtn'))return;$('#newScheduleBtn').onclick=function(){$('#scheduleEditor').classList.remove('hidden');$('#scheduleId').value='';$('#scheduleDay').value='';$('#scheduleTitle').value='';$('#scheduleTime').value='';$('#scheduleLocation').value='';$('#scheduleSort').value='0'};$('#cancelScheduleBtn').onclick=function(){$('#scheduleEditor').classList.add('hidden')};$('#saveScheduleBtn').onclick=function(){api().post({action:'saveSchedule',token:state.token,id:$('#scheduleId').value,day:$('#scheduleDay').value,title:$('#scheduleTitle').value,time:$('#scheduleTime').value,location:$('#scheduleLocation').value,sort:Number($('#scheduleSort').value||0)}).then(function(){toast('برنامه ذخیره شد ✓');$('#scheduleEditor').classList.add('hidden');loadSchedule()}).catch(function(e){toast(e.message,1)})};loadSchedule()}
function toggleStaff(){
 var panel=$('#coachStaffPanel'); if(!panel)return; panel.classList.toggle('hidden',!state.isMaster);
 if(state.isMaster)loadCoaches();
}
function loadCoaches(){
 if(!state.isMaster)return;
 api().get({action:'listCoaches',token:state.token}).then(function(r){
  var list=r.items||[];$('#coachList').innerHTML=list.map(function(x){return '<div class="admin-item"><div class="admin-item-main"><strong>'+esc(x.name)+'</strong><small>'+esc(x.phone)+' · '+(x.role==='master'?'مربی ارشد':'مربی')+'</small></div></div>'}).join('');
 }).catch(function(e){toast(e.message,1)});
}
function setupCoachManagement(){
 var b=$('#addCoachBtn');if(!b)return;
 b.onclick=function(){
  api().post({action:'addCoach',token:state.token,name:$('#newCoachName').value.trim(),phone:$('#newCoachPhone').value.trim(),code:$('#newCoachCode').value.trim()})
   .then(function(){toast('مربی اضافه شد ✓');$('#newCoachName').value='';$('#newCoachPhone').value='';$('#newCoachCode').value='';loadCoaches()})
   .catch(function(e){toast(e.message,1)});
 };
}
function init(){state.token=sessionStorage.getItem('coach_token')||'';state.name=sessionStorage.getItem('coach_name')||'';state.isMaster=sessionStorage.getItem('coach_master')==='1';setupSchedule();if(state.token){$('#coachLogin').classList.add('hidden');$('#coachDashboard').classList.remove('hidden');$('#coachName').textContent=state.name;toggleStaff();setTimeout(load,0)}else login();$('#newEventBtn').onclick=function(){openEditor(null)};$('#cancelEventBtn').onclick=function(){$('#eventEditor').classList.add('hidden')};$('#saveEventBtn').onclick=saveEvent;$('#savePrizeBtn').onclick=function(){api().post({action:'saveGamePrize',token:state.token,prize:$('#gamePrize').value.trim()}).then(function(){toast('جایزه ذخیره شد ✓')}).catch(function(e){toast(e.message,1)})};$('#coachLogout').onclick=function(){sessionStorage.removeItem('coach_token');sessionStorage.removeItem('coach_name');sessionStorage.removeItem('coach_master');location.reload()}}
setupCoachManagement();
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();