(function(){'use strict';
var canvas=document.getElementById('gameCanvas'),ctx=canvas&&canvas.getContext('2d');if(!canvas)return;
var start=document.getElementById('startGame'),scoreEl=document.getElementById('score'),bestEl=document.getElementById('best'),nameBox=document.getElementById('nameBox'),prize=document.getElementById('prizeText'),board=document.getElementById('leaderboardList');
var W=420,H=560,bird,pipes,score,running,raf,last,submitted=false,best=Number(localStorage.getItem('flappyBest')||0);
bestEl.textContent=best.toLocaleString('fa-IR');
function api(){return window.KanoonApp&&window.KanoonApp.api}
function load(){if(!api())return;api().get({action:'getGameData'}).then(function(r){prize.textContent=r.prize||'به بیشترین رکورد هفته جایزه داده می شود';renderBoard(r.leaderboard||[])}).catch(function(){});}
function renderBoard(list){board.innerHTML=list.length?list.map(function(x,i){return '<div class="leader-row"><span class="rank">'+(i+1).toLocaleString('fa-IR')+'</span><span class="leader-name">'+esc(x.playerName)+'</span><span class="leader-score">'+Number(x.score).toLocaleString('fa-IR')+'</span></div>'}).join(''):'<div class="empty"><p>هنوز رکوردی ثبت نشده</p></div>'}
function esc(s){return String(s||'').replace(/[&<>"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]})}
function reset(){bird={x:82,y:H/2,vy:0,r:14};pipes=[];score=0;running=true;submitted=false;nameBox.classList.add('hidden');last=performance.now();start.textContent='در حال بازی...';spawn();raf=requestAnimationFrame(loop)}
function spawn(){pipes.push({x:W+30,gap:145,top:70+Math.random()*250,passed:false})}
function flap(){if(!running)return;bird.vy=-6.8}
function draw(){ctx.clearRect(0,0,W,H);var g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#9bd9e9');g.addColorStop(1,'#f5e7bc');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#c6a24a';ctx.fillRect(0,H-38,W,38);pipes.forEach(function(p){ctx.fillStyle='#244a3b';ctx.fillRect(p.x,0,48,p.top);ctx.fillRect(p.x,p.top+p.gap,48,H);ctx.fillStyle='#d6b25a';ctx.fillRect(p.x-4,p.top-10,56,10);ctx.fillRect(p.x-4,p.top+p.gap,56,10)});ctx.save();ctx.translate(bird.x,bird.y);ctx.rotate(Math.max(-.35,Math.min(.7,bird.vy*.04)));ctx.fillStyle='#e2b948';ctx.beginPath();ctx.arc(0,0,bird.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(6,-4,4,0,Math.PI*2);ctx.fill();ctx.fillStyle='#172338';ctx.beginPath();ctx.arc(7,-4,2,0,Math.PI*2);ctx.fill();ctx.fillStyle='#b84a37';ctx.beginPath();ctx.moveTo(13,2);ctx.lineTo(25,6);ctx.lineTo(13,9);ctx.fill();ctx.restore();ctx.fillStyle='#172338';ctx.font='800 28px Vazirmatn';ctx.fillText(String(score),W/2-8,46)}
function loop(t){if(!running)return;var dt=Math.min(32,t-last);last=t;bird.vy+=.36*(dt/16);bird.y+=bird.vy*(dt/16);pipes.forEach(function(p){p.x-=2.8*(dt/16);if(!p.passed&&p.x+48<bird.x){p.passed=true;score++;scoreEl.textContent=score.toLocaleString('fa-IR');}});if(pipes.length&&pipes[0].x<-70)pipes.shift();if(!pipes.length||pipes[pipes.length-1].x<W-185)spawn();var hit=bird.y+bird.r>H-38||bird.y-bird.r<0;pipes.forEach(function(p){if(bird.x+bird.r>p.x&&bird.x-bird.r<p.x+48&&(bird.y-bird.r<p.top||bird.y+bird.r>p.top+p.gap))hit=true});draw();if(hit){end();return}raf=requestAnimationFrame(loop)}
function end(){running=false;cancelAnimationFrame(raf);if(score>best){best=score;localStorage.setItem('flappyBest',best);bestEl.textContent=best.toLocaleString('fa-IR')}start.textContent='دوباره بازی کن';if(score>0)nameBox.classList.remove('hidden')}
function submit(){var n=(document.getElementById('playerName').value||'').trim();if(!n||!api()){return}api().post({action:'submitGameScore',playerName:n,score:score}).then(function(r){renderBoard(r.leaderboard||[]);nameBox.classList.add('hidden');window.KanoonApp.toast.success('رکورد ثبت شد ✓')}).catch(function(e){window.KanoonApp.toast.error(e.message||'خطا در ثبت رکورد')})}
canvas.addEventListener('pointerdown',flap);document.addEventListener('keydown',function(e){if(e.code==='Space'){e.preventDefault();flap()}});start.addEventListener('click',function(){if(!running)reset()});document.getElementById('submitScore').addEventListener('click',submit);draw();load();
})();