(function(){'use strict';
var $=function(s){return document.querySelector(s)},canvas=$('#snakeCanvas'),ctx=canvas&&canvas.getContext('2d');if(!canvas||!ctx)return;
var W=420,H=560,CELL=20,COLS=21,ROWS=28,gate=$('#snakeGate'),content=$('#snakeContent'),gateMessage=$('#snakeGateMessage'),start=$('#snakeStart'),scoreEl=$('#snakeScore'),bestEl=$('#snakeBest');
var snake=[],dir={x:1,y:0},nextDir={x:1,y:0},food=null,score=0,best=Number(localStorage.getItem('snakeBest')||0),running=false,timer=null,stepMs=145,lastTouch=null,faceIndex=0,audio=null;
var faces=[{name:'ترامپ',skin:'#efc49c',hair:'#e9b84e',tie:'#bd3434',style:0},{name:'نتانیاهو',skin:'#e4b58d',hair:'#d4d6d9',tie:'#293d66',style:1},{name:'اپستین',skin:'#e4b58f',hair:'#4b403b',tie:'#6a2938',style:2},{name:'بایدن',skin:'#e9c5a3',hair:'#d8dce1',tie:'#2b4d85',style:3},{name:'اوباما',skin:'#9a6246',hair:'#27272a',tie:'#6d2535',style:4},{name:'بوش',skin:'#e4b58e',hair:'#9a7550',tie:'#294c77',style:5},{name:'کلینتون',skin:'#e7bd98',hair:'#b5b6b8',tie:'#713c8e',style:6},{name:'ریگان',skin:'#e6ba95',hair:'#c2b39b',tie:'#a83434',style:7}];
bestEl.textContent=fmt(best);
function fmt(n){return Number(n||0).toLocaleString('fa-IR')}
function app(){return window.KanoonApp}
function showGate(message){gate.classList.remove('hidden');content.classList.add('hidden');if(message)gateMessage.textContent=message}
function showGame(){gate.classList.add('hidden');content.classList.remove('hidden');draw()}
async function boot(){var attempts=0;while((!app()||!app().session)&&attempts++<60)await new Promise(function(r){setTimeout(r,50)});var member=app()&&app().session&&app().session.getMember();if(!member||!member.token){showGate('بازی فقط برای اعضای حلقه است. برای درخواست عضویت از دکمه زیر استفاده کن.');return}
 try{var status=await app().api.get({action:'getCircleMembership',token:member.token});if(status.isMember){showGame()}else showGate(status.status==='در انتظار بررسی'?'درخواستت ثبت شده و هنوز تأیید نشده است. بازی پس از تأیید عضویت باز می‌شود.':'بازی فقط برای اعضای حلقه است. برای درخواست عضویت از دکمه زیر استفاده کن.')}
 catch(e){showGate('وضعیت عضویت دریافت نشد. اتصال اینترنت را بررسی و صفحه را دوباره باز کن.')}
}
function playCrunch(){try{var AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;if(!audio)audio=new AC();if(audio.state==='suspended')audio.resume();var length=Math.floor(audio.sampleRate*.12),buffer=audio.createBuffer(1,length,audio.sampleRate),data=buffer.getChannelData(0);for(var i=0;i<length;i++){var envelope=Math.pow(1-i/length,2);data[i]=(Math.random()*2-1)*envelope*(i%5===0?1:.48)}var noise=audio.createBufferSource();noise.buffer=buffer;var filter=audio.createBiquadFilter();filter.type='lowpass';filter.frequency.value=1900;var gain=audio.createGain();gain.gain.value=.28;noise.connect(filter);filter.connect(gain);gain.connect(audio.destination);noise.start();var osc=audio.createOscillator(),og=audio.createGain();osc.type='triangle';osc.frequency.setValueAtTime(210,audio.currentTime);osc.frequency.exponentialRampToValueAtTime(75,audio.currentTime+.09);og.gain.setValueAtTime(.16,audio.currentTime);og.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.1);osc.connect(og);og.connect(audio.destination);osc.start();osc.stop(audio.currentTime+.11)}catch(e){}}
function randomFood(){var p;do{p={x:Math.floor(Math.random()*COLS),y:Math.floor(Math.random()*ROWS),face:Math.floor(Math.random()*faces.length)}}while(snake.some(function(s){return s.x===p.x&&s.y===p.y}));food=p}
function startGame(){if(running)return;snake=[{x:6,y:14},{x:5,y:14},{x:4,y:14},{x:3,y:14}];dir={x:1,y:0};nextDir={x:1,y:0};score=0;faceIndex=0;scoreEl.textContent=fmt(score);randomFood();running=true;start.textContent='در حال بازی...';start.classList.add('playing');start.classList.remove('finished');if(timer)clearInterval(timer);timer=setInterval(tick,stepMs);draw()}
function endGame(){running=false;if(timer)clearInterval(timer);timer=null;start.classList.remove('playing');start.classList.add('finished');start.textContent='دوباره بازی کن';if(score>best){best=score;localStorage.setItem('snakeBest',String(best));bestEl.textContent=fmt(best)}draw(true)}
function changeDirection(x,y){if(!running)return;if(x===-dir.x&&y===-dir.y)return;nextDir={x:x,y:y}}
function tick(){dir=nextDir;var head={x:snake[0].x+dir.x,y:snake[0].y+dir.y};if(head.x<0||head.y<0||head.x>=COLS||head.y>=ROWS||snake.some(function(p,i){return i<snake.length-1&&p.x===head.x&&p.y===head.y})){endGame();return}snake.unshift(head);if(food&&head.x===food.x&&head.y===food.y){score++;scoreEl.textContent=fmt(score);faceIndex=food.face;playCrunch();randomFood();if(stepMs>80){stepMs-=1;clearInterval(timer);timer=setInterval(tick,stepMs)}}else snake.pop();draw()}
function roundedRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect?ctx.roundRect(x,y,w,h,r):(ctx.rect(x,y,w,h));ctx.fill()}
function drawFace(x,y,size,face){var cx=x+size/2,cy=y+size/2;ctx.save();ctx.shadowColor='rgba(18,37,52,.2)';ctx.shadowBlur=5;ctx.fillStyle=face.skin;ctx.beginPath();ctx.ellipse(cx,cy,size*.37,size*.42,0,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;
 ctx.fillStyle=face.hair;if(face.style===0){ctx.beginPath();ctx.ellipse(cx,cy-size*.25,size*.4,size*.22,-.12,Math.PI,Math.PI*2);ctx.fill();ctx.fillRect(cx-size*.36,cy-size*.26,size*.7,size*.12)}else if(face.style===1||face.style===3||face.style===6||face.style===7){ctx.beginPath();ctx.ellipse(cx,cy-size*.29,size*.37,size*.15,0,Math.PI,Math.PI*2);ctx.fill()}else{ctx.beginPath();ctx.ellipse(cx,cy-size*.3,size*.35,size*.15,0,Math.PI,Math.PI*2);ctx.fill()}
 ctx.fillStyle='#26313c';ctx.beginPath();ctx.arc(cx-size*.13,cy-size*.02,size*.035,0,Math.PI*2);ctx.arc(cx+size*.13,cy-size*.02,size*.035,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#855f4c';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(cx-size*.09,cy+size*.15);ctx.quadraticCurveTo(cx,cy+size*.2,cx+size*.09,cy+size*.15);ctx.stroke();
 if(face.style===2||face.style===4){ctx.fillStyle=face.style===4?'#292729':'#b8b8b8';ctx.beginPath();ctx.ellipse(cx,cy+size*.19,size*.23,size*.13,0,0,Math.PI);ctx.fill()}
 ctx.fillStyle=face.tie;ctx.beginPath();ctx.moveTo(cx-size*.12,cy+size*.33);ctx.lineTo(cx+size*.12,cy+size*.33);ctx.lineTo(cx+size*.18,cy+size*.49);ctx.lineTo(cx,cy+size*.58);ctx.lineTo(cx-size*.18,cy+size*.49);ctx.closePath();ctx.fill();ctx.restore()}
function drawSnakeSegment(s,i){var x=s.x*CELL,y=s.y*CELL;ctx.fillStyle=i===0?'#147d68':i%2?'#259c80':'#1b8c75';roundedRect(x+1,y+1,CELL-2,CELL-2,6);if(i===0){ctx.fillStyle='#fff';var ex=x+CELL/2+(dir.x===1?4:dir.x===-1?-4:0),ey=y+CELL/2+(dir.y===1?4:dir.y===-1?-4:0);ctx.beginPath();ctx.arc(ex-3,ey-3,2.4,0,Math.PI*2);ctx.arc(ex+3,ey-3,2.4,0,Math.PI*2);ctx.fill();ctx.fillStyle='#14283b';ctx.beginPath();ctx.arc(ex-3,ey-3,1.1,0,Math.PI*2);ctx.arc(ex+3,ey-3,1.1,0,Math.PI*2);ctx.fill()}}
function draw(over){ctx.clearRect(0,0,W,H);var g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,'#e7f2e8');g.addColorStop(1,'#cbded4');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(32,91,72,.08)';ctx.lineWidth=1;for(var x=0;x<=W;x+=CELL){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(var y=0;y<=H;y+=CELL){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}if(food){drawFace(food.x*CELL+1,food.y*CELL+1,CELL-2,faces[food.face]);ctx.fillStyle='#183a30';ctx.font='700 10px Vazirmatn';ctx.textAlign='center';ctx.fillText(faces[food.face].name,food.x*CELL+CELL/2,food.y*CELL+CELL+1)}snake.forEach(drawSnakeSegment);if(!running){ctx.fillStyle='rgba(13,32,45,.68)';ctx.fillRect(0,0,W,H);ctx.textAlign='center';ctx.fillStyle='#fff';ctx.font='800 24px Vazirmatn';ctx.fillText(over?'پایان بازی':'آماده‌ای؟',W/2,H/2-8);ctx.font='500 13px Vazirmatn';ctx.fillStyle='#e1c16a';ctx.fillText(over?'امتیاز: '+fmt(score):'برای شروع دکمه را بزن',W/2,H/2+24)}ctx.textAlign='start'}
canvas.addEventListener('pointerdown',function(e){var rect=canvas.getBoundingClientRect();lastTouch={x:e.clientX,y:e.clientY};});
canvas.addEventListener('pointerup',function(e){if(!lastTouch||!running)return;var dx=e.clientX-lastTouch.x,dy=e.clientY-lastTouch.y;if(Math.max(Math.abs(dx),Math.abs(dy))>16){if(Math.abs(dx)>Math.abs(dy))changeDirection(dx>0?1:-1,0);else changeDirection(0,dy>0?1:-1)}lastTouch=null});
document.addEventListener('keydown',function(e){var k=e.key;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].indexOf(k)<0)return;e.preventDefault();if(k==='ArrowUp'||k==='w')changeDirection(0,-1);if(k==='ArrowDown'||k==='s')changeDirection(0,1);if(k==='ArrowLeft'||k==='a')changeDirection(-1,0);if(k==='ArrowRight'||k==='d')changeDirection(1,0)});
document.querySelectorAll('[data-dir]').forEach(function(b){b.addEventListener('click',function(){var d=b.getAttribute('data-dir');if(d==='up')changeDirection(0,-1);if(d==='down')changeDirection(0,1);if(d==='left')changeDirection(-1,0);if(d==='right')changeDirection(1,0)})});
start.addEventListener('click',startGame);draw();boot();
})();